# Generated by Django 3.2.19 on 2023-11-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(
                blank=True,
                default='default.jpg',
                null=True,
                upload_to='profile_pictures'),
        ),
    ]
