# Generated by Django 3.2.19 on 2023-06-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230619_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subreddit',
            field=models.CharField(max_length=50),
        ),
    ]
